"""initial schema

Revision ID: b556f22d8092
Revises: None
Create Date: 2026-03-18 12:10:22.617781
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b556f22d8092'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ensemble_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('G', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.BigInteger(), nullable=True),
    sa.Column('followup_notifications', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_ensemble_id'), 'schedules', ['ensemble_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=True),
    sa.Column('rehearsal_num', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_rehearsal_num'), 'attendance', ['rehearsal_num'], unique=False)
    op.create_index(op.f('ix_attendance_schedule_id'), 'attendance', ['schedule_id'], unique=False)
    op.create_index('ix_attendance_schedule_rehearsal_user', 'attendance', ['schedule_id', 'rehearsal_num', 'user_id'], unique=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_schedule_id'), 'audit_entries', ['schedule_id'], unique=False)
    op.create_table('rehearsals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=True),
    sa.Column('rehearsal_num', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rehearsals_rehearsal_num'), 'rehearsals', ['rehearsal_num'], unique=False)
    op.create_index(op.f('ix_rehearsals_schedule_id'), 'rehearsals', ['schedule_id'], unique=False)
    op.create_table('timed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=True),
    sa.Column('rehearsal_num', sa.Integer(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timed_items_rehearsal_num'), 'timed_items', ['rehearsal_num'], unique=False)
    op.create_index(op.f('ix_timed_items_schedule_id'), 'timed_items', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timed_items_schedule_id'), table_name='timed_items')
    op.drop_index(op.f('ix_timed_items_rehearsal_num'), table_name='timed_items')
    op.drop_table('timed_items')
    op.drop_index(op.f('ix_rehearsals_schedule_id'), table_name='rehearsals')
    op.drop_index(op.f('ix_rehearsals_rehearsal_num'), table_name='rehearsals')
    op.drop_table('rehearsals')
    op.drop_index(op.f('ix_audit_entries_schedule_id'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    op.drop_index('ix_attendance_schedule_rehearsal_user', table_name='attendance')
    op.drop_index(op.f('ix_attendance_schedule_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_rehearsal_num'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_schedules_ensemble_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
